version: '1.0'
services:
  postgres:
    image: postgres:latest
    env_file:
      - postgres.env
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    env_file:
      - app.env